#!/bin/bash

# set prompt
export PS1="\n\[\e[1m\]\[\e[33m\w\]\[\e[33m\] $ \[\e[0m\]"

# enable bash completion
source /etc/bash_completion

# go to /workspace directory
cd /workspace

# export env vars
export JAVA_HOME=/usr/lib/jvm/default-java/jre

# set aliases
# Generate args to highlight changed lines for bat
BAT_LANG=""
batdf() { hArgs=$(diff --unchanged-line-format="" --old-line-format="" --new-line-format="%dn " ${1} ${2} | xargs -n1 -I {} printf -- '-H %s:%s ' {} {}); bat ${BAT_LANG} ${2} $hArgs; }
alias batd=batdf
setBatLangf() { if [[ "${1}" == "" ]]; then export BAT_LANG=""; else export BAT_LANG="-l ${1}"; fi; alias bat="bat ${BAT_LANG}"; }
alias setBatLang=setBatLangf
setBatLang ""
# Usage example:
# setBatLang Dockerfile
# bat Dockerfile
# batd Dockerfile Dockerfile2
# setBatLang exclude
# bat .dockerignore
# batd .dockerignore .dockerignore2
# To use default language detection, set to empty string:
# setBatLang

setBatLang Dockerfile

# export ENV_STATUS to display in intro-foreground.sh
export ENV_STATUS="Environment ready!"
